name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: download kernel
        run: |
          git clone https://github.com/leandrotsampa/hisilicon-kernel3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install make imagemagick ttf-dejavu gcc-arm-embedded

      - name: Download toolchain
        run: |
          curl -L -O https://redirect.armbian.com/_toolchain/gcc-linaro-arm-none-eabi-4.8-2014.04_linux.tar.xz
          tar xvf ./gcc-linaro-arm-none-eabi-4.8-2014.04_linux.tar.xz

      - name: Build
        run: |
          export PATH="$PATH:$(pwd)/gcc-linaro-arm-none-eabi-4.8-2014.04_linux/bin"
          export ARCH=arm           # Set Kernel Arch
          export CROSS_COMPILE=arm-linux-gnueabi- # Set Compiler
          export CONFIG_MSP=y # Enable Hisilicon

          cd hisilicon-kernel3
          make hi3798cv200_linux_defconfig
          make uImage
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/*.bin
            build/uImage*


      - name: Release
        run: |
          time="${{ github.event.head_commit.timestamp }}"
          sha="${GITHUB_SHA:0:8}"
          tag="build-$(date +'%Y%m%d-%H%M' -d "$time")"
          message="Auto-Build $(date +'%Y-%m-%d %H:%M' -d "$time")"
          hub release create  -t "$GITHUB_SHA" "$tag" -m "$message" \
            $(for a in build/*.bin; do echo -a $a; done) \
            $(for a in build/uImage*; do echo -a $a; done)
        env:
          GITHUB_TOKEN: ${{ github.token }}
